/**
 * Project Time Machine stages.
 *
 * Five illustrative stages of a data-center build. Each maps to evidence the
 * project already stores, so dragging the as-of slider moves a site up the
 * ladder exactly when the records say it did.
 *
 * The clips are ONE generic set reused for all projects - they are an
 * illustration of a stage, never a picture of a specific site. Every surface
 * that renders one must say so (see StageClip).
 */

export type StageId = "filed" | "certified" | "construction" | "complete" | "energized";

export interface Stage {
  id: StageId;
  /** Ascending; higher means further along. */
  rank: number;
  label: string;
  /** What in the record puts a project here, shown under the clip. */
  basis: string;
  /** Video served from public/illustrations, generated by etl/generate_imagery.py. */
  clip: string;
  /** Still of the same stage, shown while the clip loads. */
  poster: string;
}

export const STAGES: Stage[] = [
  {
    id: "filed",
    rank: 0,
    label: "Request filed",
    basis: "A public record exists, but no construction signal yet",
    clip: "/illustrations/filed.mp4",
    poster: "/illustrations/filed.jpg",
  },
  {
    id: "certified",
    rank: 1,
    label: "Site certified",
    basis: "Comptroller certification or TDLR design review complete",
    clip: "/illustrations/certified.mp4",
    poster: "/illustrations/certified.jpg",
  },
  {
    id: "construction",
    rank: 2,
    label: "Under construction",
    basis: "TDLR building registration filed",
    clip: "/illustrations/construction.mp4",
    poster: "/illustrations/construction.jpg",
  },
  {
    id: "complete",
    rank: 3,
    label: "Buildings complete",
    basis: "TDLR inspection complete",
    clip: "/illustrations/complete.mp4",
    poster: "/illustrations/complete.jpg",
  },
  {
    id: "energized",
    rank: 4,
    label: "Energized",
    /**
     * NOTE: nothing in the corpus reports energization today. TDLR's "Project
     * Closed" means the permit file was closed, which is an administrative
     * fact, not proof that load is being served - mapping it here would be
     * inventing evidence. This stage stays unreachable until an interconnection
     * or utility energization feed is added.
     */
    basis: "Not yet derivable - no energization source in the corpus",
    clip: "/illustrations/energized.mp4",
    poster: "/illustrations/energized.jpg",
  },
];

export const STAGE_BY_ID = Object.fromEntries(STAGES.map((s) => [s.id, s])) as Record<StageId, Stage>;

/** Highest stage the evidence supports at the selected as-of date. */
export function stageFor(input: {
  factors?: Record<string, boolean> | null;
  currentStatus?: string | null;
  hasAnyEvidence?: boolean;
}): Stage | null {
  const f = input.factors ?? {};
  const status = input.currentStatus ?? null;

  // Scored factors are computed per week, so they already respect as-of. Status
  // is a lighter-touch signal used only to lift a project that has a TDLR
  // milestone the checklist does not cover.
  if (f.inspection_done || status === "inspection_complete") return STAGE_BY_ID.complete;
  if (f.tdlr_registered || status === "registered") return STAGE_BY_ID.construction;
  if (f.comptroller_certified || f.tceq_permit || status === "design_review_complete") return STAGE_BY_ID.certified;
  if (input.hasAnyEvidence || Object.values(f).some(Boolean)) return STAGE_BY_ID.filed;
  return null;
}

/**
 * Same ladder as stageFor, expressed over the fields a Site row carries.
 * Org listings do not load per-site scoring factors, so this reads the
 * equivalent columns instead - deliberately the same rungs in the same order,
 * so a site shows the same stage wherever it is listed.
 */
export function stageForSite(site: {
  inspected?: boolean;
  tdlr_registrations?: number;
  certified_at?: string | null;
  has_permit?: boolean;
  first_evidence?: string | null;
}): Stage | null {
  if (site.inspected) return STAGE_BY_ID.complete;
  if ((site.tdlr_registrations ?? 0) > 0) return STAGE_BY_ID.construction;
  if (site.certified_at || site.has_permit) return STAGE_BY_ID.certified;
  if (site.first_evidence) return STAGE_BY_ID.filed;
  return null;
}
