"use client";
import { useCallback, useEffect, useRef, useState } from "react";

/**
 * Hero reel: four unrelated held takes that cut between hard palette changes.
 *
 * All four are rendered stacked and cross-faded by opacity, so there is no
 * black flash from swapping a single <video>'s src. Only the active clip is
 * played; the rest stay paused and unloaded until their turn, which keeps the
 * first paint cheap even though the set is ~17MB.
 *
 * Clips are generated by etl/generate_imagery.py --set hero, with prompt,
 * model and hash recorded in public/hero/manifest.json.
 */

// arc is first on purpose: it is the only near-black clip, so the headline
// lands on it cleanly while the brighter three are still loading.
const CLIPS = [
  { src: "/hero/arc.mp4", alt: "High-voltage insulator arcing at night" },
  { src: "/hero/water.mp4", alt: "Turbulent water and light shafts below the surface" },
  { src: "/hero/salt.mp4", alt: "Cracked salt flat stretching to the horizon" },
  { src: "/hero/arm.mp4", alt: "Robotic arm moving in a clean room" },
];

export default function HeroReel() {
  const [active, setActive] = useState(0);
  const refs = useRef<Array<HTMLVideoElement | null>>([]);

  const advance = useCallback(() => setActive((i) => (i + 1) % CLIPS.length), []);

  useEffect(() => {
    // Honour a reduced-motion preference by holding on the first frame.
    const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    refs.current.forEach((v, i) => {
      if (!v) return;
      if (i === active && !reduce) {
        v.currentTime = 0;
        void v.play().catch(() => {});
      } else {
        v.pause();
      }
    });
    if (reduce) return;
    // Belt and braces: if a clip stalls, move on rather than freezing the hero.
    const t = setTimeout(advance, 9000);
    return () => clearTimeout(t);
  }, [active, advance]);

  return (
    <div className="absolute inset-0 overflow-hidden rounded-2xl bg-black">
      {CLIPS.map((clip, i) => (
        <video
          key={clip.src}
          ref={(el) => {
            refs.current[i] = el;
          }}
          className={`absolute inset-0 h-full w-full object-cover transition-opacity duration-1000 ${
            i === active ? "opacity-100" : "opacity-0"
          }`}
          src={clip.src}
          // Only the first clip is worth fetching up front.
          preload={i === 0 ? "auto" : "none"}
          muted
          playsInline
          onEnded={advance}
          aria-label={clip.alt}
        />
      ))}

      {/* Scrim. Two of the four clips are bright (salt, arm), so the copy needs
          its own dark ground rather than relying on the footage. */}
      <div
        aria-hidden
        className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/45 to-black/20"
      />
    </div>
  );
}
